server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      #      discovery.locator:
      #        enable: true
      #        lowerCaseServiceId: true
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*, /$\{path}

  application:
    name: gateway-server